export const JOB_TYPES: Record<string, string> = {
  trans: "Translation",
  inter: "Interpreting",
  check_edit: "Editing/proofreading",
  manag: "Project management",
  formatting: "DTP/Formatting",
  website_loc: "Website localization",
  software_loc: "Software localization",
  voiceover: "Voiceover (dubbing)",
  subtitling: "Subtitling",
  post_editing: "Post-editing",
  transcription: "Transcription",
  training: "Training session",
  desktop_publishing: "Desktop publishing",
  vendor_manag: "Vendor management",
  sales: "Sales",
  operations_manag: "Operations management",
  copywriting: "Copywriting",
  summarization: "Summarization",
  transcreation: "Transcreation",
};
